<a href="https://colab.research.google.com/github/DoctaSTEPHEN/CPE-311--Computational-Thinking-with-Python/blob/main/Hands_on_Activity_5_1_Text_Similarity_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Activity 5.1 Text Similarity

#### Objective(s):

This activity aims to introduce how to implement text similarity

#### Intended Learning Outcomes (ILOs):
* Demonstrate how to remove special characters from text
* Demonstrate how to measure text simiarity using distance
* Demonstrate how to find text similarity using Count Vector and TF-IDF Vectorizer

#### Resources:
* Jupyter Notebook
* songdata.csv

#### Procedures
Load the necessary libraries

In [ ]:
import nltk
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/CPE 313/songdata.csv')
data.head()

,artist,song,link,text
0,ABBA,Ahe's My Kind Of Girl,/a/abba/ahes+my+kind+of+girl_20598417.html,"Look at her face, it's a wonderful face \r\nA..."
1,ABBA,"Andante, Andante",/a/abba/andante+andante_20002708.html,"Take it easy with me, please \r\nTouch me gen..."
2,ABBA,As Good As New,/a/abba/as+good+as+new_20003033.html,I'll never know why I had to go \r\nWhy I had...
3,ABBA,Bang,/a/abba/bang_20598415.html,Making somebody happy is a question of give an...
4,ABBA,Bang-A-Boomerang,/a/abba/bang+a+boomerang_20002668.html,Making somebody happy is a question of give an...

Find the lyrics by the artist The Beatles

In [ ]:
beatles = data[data.artist=='The Beatles']
beatles.head()

,artist,song,link,text
1198,The Beatles,A Shot Of Rhythm And Blues,/b/beatles/a+shot+of+rhythm+blues_20014867.html,"Well, if your hands start a-clappin' \r\nAnd ..."
1199,The Beatles,Across The Universe,/b/beatles/across+the+universe_10026507.html,Words are flowing out like \r\nEndless rain i...
1200,The Beatles,All I've Got To Do,/b/beatles/all+ive+got+to+do_10026646.html,"Whenever I want you around, yeah \r\nAll I go..."
1201,The Beatles,And I Love Her,/b/beatles/and+i+love+her_10026463.html,I give her all my love \r\nThat's all I do \...
1202,The Beatles,And Your Bird Can Sing,/b/beatles/and+your+bird+can+sing_10026364.html,You tell me that you've got everything you wan...

Check the number of Beatles songs in the data set

In [ ]:
data.artist.value_counts().loc[['The Beatles']]

artist
The Beatles    178
Name: count, dtype: int64

Take a look at the first song's lyrics

In [ ]:
beatles.iloc[0,3]

"Well, if your hands start a-clappin'  \r\nAnd your fingers start a-poppin'  \r\nAnd your feet start a-movin' around  \r\nAnd if you start to swing and sway  \r\n  \r\nWhen the band starts to play  \r\nA real cool way out sound  \r\nAnd if you get to can't help it and you can't sit down  \r\nYou feel like you gotta move around  \r\n  \r\nYou get a shot of rhythm and blues.  \r\nWith just a little rock and roll on the side  \r\nJust for good measure.  \r\nGet a pair of dancin' shoes  \r\n  \r\nWell, with your lover by your side  \r\nDon't you know you're gonna have a rockin' time, see'mon!  \r\nDon't you worry 'bout a thing  \r\nIf you start to dance and sing  \r\n  \r\nAnd chills come up on you  \r\nAnd if the rhythm finally gets you and the beat gets you too  \r\nWell, here's something for you to do  \r\n  \r\nGet a shot of rhythm and blues  \r\nWith just a little rock and roll on the side  \r\nJust for good measure  \r\nGet a pair of dancin' shoes  \r\n  \r\nWell, with your lover by your side  \r\nDon't you know you're gonna have a rockin' time, see'mon!  \r\nDon't you worry 'bout a thing  \r\nIf you start to dance and sing  \r\n  \r\nAnd chills come up on you  \r\nAnd if the rhythm finally gets you and the beat gets you too  \r\nWell, here's something for you to do  \r\n  \r\nGet a shot of rhythm and blues  \r\nGet a pair of dancin' shoes  \r\nGet a shot of rhythm and blues  \r\nWell, with your lover by your side  \r\n  \r\nDon't you know you're gonna have a rockin' time, see'mon!  \r\nDon't you worry 'bout a thing  \r\nIf you start to dance and sing  \r\nAnd chills come up on you  \r\n  \r\nAnd if the rhythm finally gets you and the beat gets you too  \r\nWell, here's something for you to do  \r\nWell, here's something for you to do  \r\nWell, here's something for you to do\r\n\r\n"

Remove characters from the lyrics

In [ ]:
import re

newline = lambda x: re.sub(r'\n', ' ', x) # remove \n
alphanumeric = lambda x: re.sub(r'\w*\d\w*', ' ', x) # remove alphanumeric words

corpus = beatles.text.map(newline).map(alphanumeric)
corpus.head()

1198    Well, if your hands start a-clappin'  \r And y...
1199    Words are flowing out like  \r Endless rain in...
1200    Whenever I want you around, yeah  \r All I got...
1201    I give her all my love  \r That's all I do  \r...
1202    You tell me that you've got everything you wan...
Name: text, dtype: object

Create a document term matrix using Count Vectorizer with the stop words turned on to English

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(stop_words="english")
X = cv.fit_transform(corpus).toarray()

dt = pd.DataFrame(X, columns=cv.get_feature_names_out()).set_index(beatles.song)
dt.head()

,aaahhh,aah,abc,aches,aching,acquainted,act,actors,acts,add,...,yes,yesterday,yoko,young,younger,youre,youu,zealand,zoo,zu
song,,,,,,,,,,,,,,,,,,,,,
A Shot Of Rhythm And Blues,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
Across The Universe,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
All I've Got To Do,0,0,0,0,0,0,0,0,0,0,...,2,0,0,0,0,0,0,0,0,0
And I Love Her,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
And Your Bird Can Sing,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

Set display options so that the lyrics aren't cut off

In [ ]:
pd.set_option('display.max_colwidth', None)

In [ ]:
beatles[beatles.song=='Imagine'].text

24783    Imagine there's no heaven  \r\nIt's easy if you try  \r\nNo hell below us  \r\nAbove us only sky  \r\nImagine all the people  \r\nLiving for today...  \r\n  \r\nImagine there's no countries  \r\nIt isn't hard to do  \r\nNothing to kill or die for  \r\nAnd no religion too  \r\nImagine all the people  \r\nLiving life in peace...  \r\n  \r\nYou may say I'm a dreamer  \r\nBut I'm not the only one  \r\nI hope someday you'll join us  \r\nAnd the world will be as one  \r\n  \r\nImagine no possessions  \r\nI wonder if you can  \r\nNo need for greed or hunger  \r\nA brotherhood of man  \r\nImagine all the people  \r\nSharing all the world...  \r\n  \r\nYou may say I'm a dreamer  \r\nBut I'm not the only one  \r\nI hope someday you'll join us  \r\nAnd the world will live as one\r\n\r\n
Name: text, dtype: object

Imagine lyrics in Count Vectorizer form

In [ ]:
imagine = list(dt.loc['Imagine'])
imagine[:20]

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

Define the cosine similarity calculation

In [ ]:
from numpy import dot
from numpy.linalg import norm

cosine = lambda v1, v2: dot(v1, v2) / (norm(v1) * norm(v2))

Calculate all similarities and sort by the most similar

In [ ]:
similarity = [cosine(imagine, song) for song in X]
sorted(list(zip(similarity, beatles.song)), reverse=True)[1:6]

[(np.float64(0.22757944185316942), "I'll Cry Instead"),
 (np.float64(0.1738270040532526), 'In My Life'),
 (np.float64(0.16574838603294895), 'Eleanor Rigby'),
 (np.float64(0.1490280831849844), 'In Spite Of All The Danger'),
 (np.float64(0.14592261028699943), 'All My Loving')]

Create the TF-IDF Vectorizer

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

cv_tfidf = TfidfVectorizer(stop_words="english")
X_tfidf = cv_tfidf.fit_transform(corpus).toarray()

dt_tfidf = pd.DataFrame(X_tfidf, columns=cv_tfidf.get_feature_names_out()).set_index(beatles.song)
dt_tfidf.head()

,aaahhh,aah,abc,aches,aching,acquainted,act,actors,acts,add,...,yes,yesterday,yoko,young,younger,youre,youu,zealand,zoo,zu
song,,,,,,,,,,,,,,,,,,,,,
A Shot Of Rhythm And Blues,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Across The Universe,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
All I've Got To Do,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.120483,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
And I Love Her,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
And Your Bird Can Sing,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

cv_tfidf = TfidfVectorizer(stop_words="english")
X_tfidf = cv_tfidf.fit_transform(corpus).toarray()

dt_tfidf = pd.DataFrame(X_tfidf, columns=cv_tfidf.get_feature_names_out()).set_index(beatles.song)
dt_tfidf.head()

,aaahhh,aah,abc,aches,aching,acquainted,act,actors,acts,add,...,yes,yesterday,yoko,young,younger,youre,youu,zealand,zoo,zu
song,,,,,,,,,,,,,,,,,,,,,
A Shot Of Rhythm And Blues,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Across The Universe,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
All I've Got To Do,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.120483,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
And I Love Her,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
And Your Bird Can Sing,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Calculate all similarities and sort by the most similar using the TF-IDF data

In [ ]:
similarity_tfidf = [cosine(imagine, song) for song in X_tfidf]
sorted(list(zip(similarity_tfidf, beatles.song)), reverse=True)[1:6]

[(np.float64(0.19266277925834221), "I'll Cry Instead"),
 (np.float64(0.18004423848592196), "I'll Get You"),
 (np.float64(0.1551371744116933), 'Eleanor Rigby'),
 (np.float64(0.15054395512050195), 'In My Life'),
 (np.float64(0.12306875209548622), 'Love Of The Loved')]

:Compare the lyrics of Imagine and I'll Cry Instead

In [ ]:
# Imagine lyrics
beatles[beatles.song=='Imagine'].text

24783    Imagine there's no heaven  \r\nIt's easy if you try  \r\nNo hell below us  \r\nAbove us only sky  \r\nImagine all the people  \r\nLiving for today...  \r\n  \r\nImagine there's no countries  \r\nIt isn't hard to do  \r\nNothing to kill or die for  \r\nAnd no religion too  \r\nImagine all the people  \r\nLiving life in peace...  \r\n  \r\nYou may say I'm a dreamer  \r\nBut I'm not the only one  \r\nI hope someday you'll join us  \r\nAnd the world will be as one  \r\n  \r\nImagine no possessions  \r\nI wonder if you can  \r\nNo need for greed or hunger  \r\nA brotherhood of man  \r\nImagine all the people  \r\nSharing all the world...  \r\n  \r\nYou may say I'm a dreamer  \r\nBut I'm not the only one  \r\nI hope someday you'll join us  \r\nAnd the world will live as one\r\n\r\n
Name: text, dtype: object

In [ ]:
beatles[beatles.song=='I\'ll Cry Instead'].text

24774    I've got every reason on earth to be mad  \r\n'Cause I just lost the only girl I had  \r\nIf I could get my way  \r\nI'd get myself locked up today  \r\nBut I can't, so I'll cry instead  \r\n  \r\nI've got a chip on my shoulder that's bigger that my feet  \r\nI can't talk to people that I meet  \r\nIf I could see you now  \r\nI'd try to make you sad somehow  \r\nBut I can't, so I'll cry instead  \r\n  \r\nDon't want to cry when there's people there  \r\nI get shy when they start to stare  \r\nI'm gonna hide myself away  \r\nBut I'll come back again someday  \r\n  \r\nAnd when you do you'd better hide all the girls  \r\nI'm gonna break their hearts all round the world  \r\nYes, I'm gonna break them in two  \r\nAnd show you what your lovin' man can do  \r\nUntil then I'll cry instead\r\n\r\n
Name: text, dtype: object

Compare the two lyrics based on the output

The two songs are very different because Imagine focuses on peace and unity of the world, while I’ll Cry Instead focuses on personal feelings of sadness and heartbreak. This shows they have low similarity in meaning and theme.

Find the two Beatles songs that are the most similar
* Using Count Vectorizer
* Using TF-IDF Vectorizer

Calculate the cosine similarity between all combinations of documents

In [ ]:

from itertools import combinations

pairs = list(combinations(beatles.song.index, 2)) # all song index combos
pairs_0 = list(combinations(range(len(beatles)), 2)) # all index combos starting with (0,1)
song_pairs = [(beatles.song[a_index], beatles.song[b_index]) for (a_index, b_index) in pairs]
song_pairs[:5]

[('A Shot Of Rhythm And Blues', 'Across The Universe'),
 ('A Shot Of Rhythm And Blues', "All I've Got To Do"),
 ('A Shot Of Rhythm And Blues', 'And I Love Her'),
 ('A Shot Of Rhythm And Blues', 'And Your Bird Can Sing'),
 ('A Shot Of Rhythm And Blues', 'Another Girl')]

 Calculate the cosine similarity of the Count Vectorizer document-term matrix

In [ ]:

results = [cosine(X[a_index], X[b_index]) for (a_index, b_index) in pairs_0]
sorted(zip(results, song_pairs), reverse=True)[:5]

[(np.float64(0.8548876342047523), ('All You Need Is Love', 'Love Me Do')),
 (np.float64(0.8359173188630292),
  ('If I Needed Someone', 'If I Needed Someone To Love')),
 (np.float64(0.8058125835571367), ('And I Love Her', 'Love Me Do')),
 (np.float64(0.7930110315846619), ('If I Fell', 'Love Me Do')),
 (np.float64(0.7478391382739419), ('And I Love Her', 'All You Need Is Love'))]

Calculate the cosine similarity of the TF-IDF Vectorizer document-term matrix

In [ ]:
results = [cosine(X_tfidf[a_index], X_tfidf[b_index]) for (a_index, b_index) in pairs_0]
sorted(zip(results, song_pairs), reverse=True)[:5]

[(np.float64(0.8717047783261523),
  ('If I Needed Someone', 'If I Needed Someone To Love')),
 (np.float64(0.6599353568343105), ('All You Need Is Love', 'Love Me Do')),
 (np.float64(0.6502842517883831), ('Have A Banana!', 'Crinsk Dee Night')),
 (np.float64(0.6232797327325461), ("Don't Let Me Down", 'Let It Be')),
 (np.float64(0.5275364336322863), ('If I Fell', 'Love Me Do'))]

In [ ]:
beatles[beatles.song=='All You Need Is Love'].text

24695    Love, love, love, love, love, love, love, love, love.  \r\n  \r\nThere's nothing you can do that can't be done.  \r\nNothing you can sing that can't be sung.  \r\nNothing you can say, but you can learn  \r\nHow to play the game  \r\nIt's easy.  \r\nNothing you can make that can't be made.  \r\nNo one you can save that can't be saved.  \r\nNothing you can do, but you can learn  \r\nHow to be you in time  \r\nIt's easy.  \r\n  \r\nAll you need is love, all you need is love,  \r\nAll you need is love, love. Love is all you need.  \r\nLove, love, love, love, love, love, love, love, love.  \r\nAll you need is love, all you need is love,  \r\nAll you need is love, love. Love is all you need.  \r\n  \r\nThere's nothing you can know that isn't known.  \r\nNothing you can see that isn't shown.  \r\nThere's nowhere you can be that isn't where  \r\nYou're meant to be  \r\nIt's easy.  \r\n  \r\nAll you need is love, all you need is love,  \r\nAll you need is love, love. Love is all you need.  \r\nAll you need is love. (All together now).  \r\nAll you need is love. (Everybody).  \r\nAll you need is love, love. Love is all you need.  \r\nLove is all you need.  \r\nLove is all you need  \r\n  \r\n(Yesterday)  \r\n(Oh yeah)  \r\n(She love you, yeah, yeah, yeah)  \r\n(She love you, yeah, yeah, yeah)  \r\n(Oh, yesterday)\r\n\r\n
Name: text, dtype: object

In [ ]:
beatles[beatles.song=='Love Me Do'].text

24805    Love, love me do.  \r\nYou know I love you,  \r\nI'll always be true,  \r\nSo please, love me do.  \r\nWhoa, love me do.  \r\n  \r\nLove, love me do.  \r\nYou know I love you,  \r\nI'll always be true,  \r\nSo please, love me do.  \r\nWhoa, love me do.  \r\n  \r\nSomeone to love,  \r\nSomebody new.  \r\nSomeone to love,  \r\nSomeone like you.  \r\n  \r\nLove, love me do.  \r\nYou know I love you,  \r\nI'll always be true,  \r\nSo please, love me do.  \r\nWhoa, love me do.  \r\n  \r\nLove, love me do.  \r\nYou know I love you,  \r\nI'll always be true,  \r\nSo please, love me do.  \r\nWhoa, love me do.  \r\nYeah, love me do.  \r\nWhoa, oh, love me do.\r\n\r\n
Name: text, dtype: object

In [ ]:
beatles[beatles.song=='If I Needed Someone'].text

24768    If I needed someone to love  \r\nYou're the one that I'd be thinking of  \r\nIf I needed someone  \r\n  \r\nIf I had some more time to spend  \r\nThen I guess I'd be with you my friend  \r\nIf I needed someone  \r\nHad you come some other day  \r\nThen it might not have been like this  \r\nBut you see now I'm too much in love  \r\n  \r\nCarve your number on my wall  \r\nAnd maybe you will get a call from me  \r\nIf I needed someone  \r\nAh, ah, ah, ah  \r\n  \r\nIf I had some more time to spend  \r\nThen I guess I'd be with you my friend  \r\nIf I needed someone  \r\nHad you come some other day  \r\nThen it might not have been like this  \r\nBut you see now I'm too much in love  \r\n  \r\nCarve your number on my wall  \r\nAnd maybe you will get a call from me  \r\nIf I needed someone  \r\nAh, ah\r\n\r\n
Name: text, dtype: object

In [ ]:
beatles[beatles.song=='If I Needed Someone To Love'].text

24769    If I needed someone to love  \r\nYoure the woman I'd be thinking of  \r\nIf I needed someone  \r\n  \r\nIf I had some more time to spend  \r\nThen I guess I'd be with you my friend  \r\nIf I needed someone  \r\n  \r\nHad you come some other day  \r\nThen it might not have been like this  \r\nBut you see now I'm too much in love  \r\n  \r\nCarve your number on my wall  \r\nAnd maybe you will get a call from me  \r\nIf I needed someone  \r\n  \r\nIf I had some more time to spend  \r\nThen I guess I'd be with you my friend  \r\nIf I needed someone  \r\n  \r\nHad you come some other day  \r\nThen it might not have been like this  \r\nBut you see now I'm too much in love  \r\n  \r\nCarve your number on my wall  \r\nAnd maybe you will get a call from me  \r\nIf I needed someone  \r\nIf I needed someone to love  \r\nYoure the woman I'd be thinking of  \r\nIf I needed someone  \r\n  \r\nIf I had some more time to spend  \r\nThen I guess I'd be with you my friend  \r\nIf I needed someone  \r\n  \r\nHad you come some other day  \r\nThen it might not have been like this  \r\nBut you see now I'm too much in love  \r\n  \r\nCarve your number on my wall  \r\nAnd maybe you will get a call from me  \r\nIf I needed someone  \r\n  \r\nIf I had some more time to spend  \r\nThen I guess I'd be with you my friend  \r\nIf I needed someone  \r\n  \r\nHad you come some other day  \r\nThen it might not have been like this  \r\nBut you see now I'm too much in love  \r\n  \r\nCarve your number on my wall  \r\nAnd maybe you will get a call from me  \r\nIf I needed someone\r\n\r\n
Name: text, dtype: object

In [ ]:
beatles[beatles.song=='Have A Banana!'].text

1221    [Speech]  \r\n  \r\nBrian Matthew: Is that it? Is that the end?  \r\nPaul: Yeah, yeah, that's it.  \r\nJohn: Fade, fade!  \r\nBrian: Good track. Oh, well, we'll stop there, stop there, stop there.  \r\nJohn: What an end!  \r\nBrian: Quiet! All right, George.  \r\nJohn: Fade!  \r\nBrian: Hold it!  \r\nGeorge: Oh, thank you.  \r\nJohn: Fade, you silly.  \r\nBrian: Well, we did. We did that. Oh, no! No! We've done that bit!  \r\nJohn: The train comes in now.  \r\nBrian: We did that.  \r\nJohn: Yeah.  \r\nBrian: To pove we weren't playing the record, then, you see. 'Cause,\r\notherwise, there's no point in you being here, is there? Ha, ha, ha!  \r\nJohn: Yeah, we did that, 'cause it sounds just like it, don't it?  \r\nBrian: Pretty cool lot of fellows, aren't you? Here, Ringo, have a banana,\r\ncatch!\r\n\r\n
Name: text, dtype: object

In [ ]:
beatles[beatles.song=='Crinsk Dee Night'].text

24713    [Speech]  \r\n  \r\nBrian Matthew: The next few minutes, we're in the lap of the gods and the\r\nhands of the Beatles. In my young days, when I was a lad, they used to have\r\nactors in films and now that they--  \r\nPaul: Yes?  \r\nJohn: Hey! Listen!  \r\nPaul: It's all changed, now, Brian. They're not doing that, no actors.  \r\nJohn: It's all changed, now.  \r\nBrian: But this is what I wonder. In those days, the actors used to say their\r\nbest bits were left on the cutting room floor. Did you find that?  \r\nJohn: No, no, no, those were the good bits in the film. You should have seen\r\nthe rest.  \r\nBrian: Yes?  \r\nJohn: Rubbish!  \r\nBrian: Was it, really?  \r\nJohn: Even worse, yes.  \r\nBrian: Who was worst?  \r\nJohn: Oh, Paul.  \r\nBrian: I see.  \r\nPaul: I think John was about the worst.  \r\nJohn: No, it was you.  \r\nPaul: Oh, Ringo was very good. He was. He's a good lad.  \r\nBrian: He was. They're saying he's a new Charlie Chaplin. Do you think that's\r\nright?  \r\nJohn: He was miming.  \r\nPaul: You, too, with Jason.  \r\nJohn: Oh, yes, he's an old one. Okay, Ring?  \r\nBrian: Beginning to look like that. Now, then--  \r\nRingo: All right, John. Can you hear me?  \r\nPaul: Can you hear him? Hello!  \r\nBrian: Not really. I hope not. I hope not!  \r\nJohn: We brought you the flowers, Ring.  \r\nBrian: He's not allowed to talk.  \r\nRingo: Eh?  \r\nJohn: We brought you the flowers.  \r\nRingo: Oh, good.  \r\nJohn: And the grapes.  \r\nRingo: Oh, I like grapes.  \r\nPaul: He likes grapes.  \r\nGeorge: We've been to Portugal.  \r\nBrian: Guess who's, guess who's top of the pops in Portugal, then.  \r\nAll: Who?  \r\nBrian: Los Beatles.  \r\nJohn: Los Beatles? Great, great laugh.  \r\nBrian: I don't suppose you know the title of your film in Portuguese?  \r\nJohn: No. Crinsk dee Night?  \r\nBrian: Could be. Let's hear the number, shall we?  \r\nJohn: Right\r\n\r\n
Name: text, dtype: object

Compare the results. Which Vectorizer seems to do a better job?

The results show that songs with similar themes or repeated words, especially about love, tend to have higher similarity scores. The highest similarity occurs when songs have very similar titles or lyrics, while lower scores still indicate shared themes but with more differences in wording.

TF-IDF works better because it does not just count words but also considers how important the words are. It reduces the effect of common words like “love” and focuses more on unique words, so the similarity results are more accurate compared to CountVectorizer.

#### Supplementary Activity

* Use a dataset that consists of text document
* Remove special characters
* Compare the similar document using Count Vector and TF-IDF Vectorizer
* Use the cosine similarity to measure the similarity of text

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/CPE 313/McDonald_s_Reviews.csv', encoding='latin1')
data.head()

,reviewer_id,store_name,category,store_address,latitude,longitude,rating_count,review_time,review,rating
0,1,McDonald's,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,"1,240",3 months ago,"Why does it look like someone spit on my food?\nI had a normal transaction, everyone was chill and polite, but now i dont want to eat this. Im trying not to think about what this milky white/clear substance is all over my food, i d*** sure am not coming back.",1 star
1,2,McDonald's,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,"1,240",5 days ago,"It'd McDonalds. It is what it is as far as the food and atmosphere go. The staff here does make a difference. They are all friendly, accommodating and always smiling. Makes for a more pleasant experience than many other fast food places.",4 stars
2,3,McDonald's,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,"1,240",5 days ago,Made a mobile order got to the speaker and checked it in.\nLine was not moving so I had to leave otherwise Iï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½d be late for work.\nNever got the refund in the app.\nI called them and they said I could only get my money back in person because it was stuck in the system.\nWent there in person the next day and the manager told me she wasnï¿,1 star
3,4,McDonald's,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,"1,240",a month ago,My mc. Crispy chicken sandwich was ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ customer service was quick and p,5 stars
4,5,McDonald's,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,"1,240",2 months ago,"I repeat my order 3 times in the drive thru, and she still manage to mess it up , it was suppose to be a large meal double filet of fish with large fries , no cheese . It was all wrong , they either need to pay close attention to the order being made , understand English or they need not to work at a drive thru",1 star

In [86]:
five_str = data[data.rating=='5 stars']
five_str.head()

,reviewer_id,store_name,category,store_address,latitude,longitude,rating_count,review_time,review,rating
3,4,McDonald's,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,"1,240",a month ago,My mc. Crispy chicken sandwich was ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ customer service was quick and p,5 stars
37,38,McDonald's,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,"1,240",4 months ago,The staff are very friendly and they do their job perfectly,5 stars
38,39,McDonald's,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,"1,240",3 months ago,Awesome service! Food hot! Best ever,5 stars
43,44,McDonald's,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,"1,240",7 months ago,"Been frequenting this location for a few years.Morning,mid-day and night,the food is always hot,fresh and served with a smile.",5 stars
63,64,McDonald's,Fast food restaurant,"13749 US-183 Hwy, Austin, TX 78750, United States",30.460718,-97.792874,"1,240",a year ago,"Never gotten my order wrong, employees seem to change a lot but they're consistently quick and nice. Also the prices here are lower than other locations, I don't know why but its a total welcome change haha.",5 stars

In [87]:
newline = lambda x: re.sub(r'\n', ' ', x)
unknown = lambda x: re.sub(r'[^\x00-\x7F]+', ' ', x)
alphanumeric = lambda x: re.sub(r'\w*\d\w*', ' ', x)

corpus = five_str.review.map(newline).map(unknown).map(alphanumeric)
corpus.head()

3                                                                                                                                               My mc. Crispy chicken sandwich was   customer service was quick and p
37                                                                                                                                                        The staff are very friendly and they do their job perfectly
38                                                                                                                                                                              Awesome service! Food hot!  Best ever
43                                                                                     Been frequenting this location for a few years.Morning,mid-day and night,the food is always hot,fresh and served with a smile.
63    Never gotten my order wrong, employees seem to change a lot but they're consistently quick and nice. Also the prices here are lower than other locations, I don't know why but its a total welcome change haha.
Name: review, dtype: object

In [88]:
cv = CountVectorizer(stop_words='english')
X_count = cv.fit_transform(corpus).toarray()

dt = pd.DataFrame(X_count, columns=cv.get_feature_names_out()).set_index(five_str.reviewer_id)
dt.head()

,aaand,aau,abandoned,abd,abilities,able,abosoulutly,absolute,absolutely,abundant,...,yucky,yum,yumm,yummiest,yummm,yummmm,yummy,yvette,zero,zoo
reviewer_id,,,,,,,,,,,,,,,,,,,,,
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
38,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
39,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
44,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
64,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [89]:
reviewer_64 = list(dt.loc[22155])
reviewer_64[:20]

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [90]:
similarity = [cosine(reviewer_64, review_vector) for review_vector in X_count]
sorted(list(zip(similarity, dt.index)), reverse=True)[1:6]

/tmp/ipykernel_680/519920837.py:4: RuntimeWarning: invalid value encountered in scalar divide
  cosine = lambda v1, v2: dot(v1, v2) / (norm(v1) * norm(v2))

[(np.float64(0.30372836961539346), 548),
 (np.float64(0.30372836961539346), 547),
 (np.float64(0.2975918103860657), 4540),
 (np.float64(0.2820047115484755), 6958),
 (np.float64(0.27551647958312153), 4492)]

In [91]:
cv_tfidf = TfidfVectorizer(stop_words="english")
X_tfidf = cv_tfidf.fit_transform(corpus).toarray()

dt_tfidf = pd.DataFrame(X_tfidf, columns=cv_tfidf.get_feature_names_out()).set_index(five_str.reviewer_id)
dt_tfidf.head()

,aaand,aau,abandoned,abd,abilities,able,abosoulutly,absolute,absolutely,abundant,...,yucky,yum,yumm,yummiest,yummm,yummmm,yummy,yvette,zero,zoo
reviewer_id,,,,,,,,,,,,,,,,,,,,,
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
64,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [92]:
similarity_tfidf = [cosine(reviewer_64, review_vector) for review_vector in X_tfidf]
sorted(list(zip(similarity_tfidf, dt.index)), reverse=True)[1:6]

/tmp/ipykernel_680/519920837.py:4: RuntimeWarning: invalid value encountered in scalar divide
  cosine = lambda v1, v2: dot(v1, v2) / (norm(v1) * norm(v2))

[(np.float64(0.30372836961539346), 548),
 (np.float64(0.30372836961539346), 547),
 (np.float64(0.25337860345538304), 408),
 (np.float64(0.23622268200758717), 2605),
 (np.float64(0.2329390419796392), 3513)]

In [93]:
five_str[five_str.reviewer_id==64].review

63    Never gotten my order wrong, employees seem to change a lot but they're consistently quick and nice. Also the prices here are lower than other locations, I don't know why but its a total welcome change haha.
Name: review, dtype: object

In [96]:
five_str[five_str.reviewer_id==4540].review

4539    It's a McDonald's, we've all been to McDonald's. What else can I say
Name: review, dtype: object

In [97]:
five_str[five_str.reviewer_id==408].review

407    Fast drive thru service.  Food by McDonald's
Name: review, dtype: object

#### Conclusion

To summarize the result of the output, Count Vector was based on frquently used words to find similarity, because of common words like "McDonald's." TF-IDF, on the other hand, was based on important words like "fast" and "food." Although both algorithms detected similar short sentences, TF-IDF is more relevant.

In conclusion, from this activity, I have learned that the similarity of the texts depends on the words used and their importance. The Count Vectorizer method identifies similarity based on the common words between the texts, which may not be the case for the TF-IDF method. The TF-IDF method gives a more accurate result compared to the other method, as it reduces the influence of common words and highlights meaningful terms.